# Generated by Django 3.2.18 on 2023-04-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230421_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorites',
            options={'ordering': ['user_id']},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Recipe', 'verbose_name_plural': 'Recipies'},
        ),
        migrations.AlterModelOptions(
            name='shopingcart',
            options={'ordering': ['user'], 'verbose_name': 'Shopping list', 'verbose_name_plural': 'Shopping lists'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7, unique=True),
        ),
    ]
