# Generated by Django 3.2.18 on 2023-05-03 21:46

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_alter_recipeingredient_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(validators=[recipes.validators.MinValueValidator(1)], verbose_name='Cooking time, minutes'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipes', verbose_name='Food photo'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.FloatField(default=1, validators=[recipes.validators.MinValueValidator(is_included=False, limit_value=0)], verbose_name='Ingredient amount'),
        ),
    ]
