

class Setup:
    MAX_INGREDIENT_NAME_LENGTH = 200
    MAX_MEASUREMENT_UNIT_LENGTH = 20
    MIN_RECIPE_NAME_LENGTH = 1
    MAX_RECIPE_NAME_LENGTH = 200
    COOKING_TIME_MIN_VALUE = 1
    INGREDIENT_AMOUNT_MIN_VALUE = 0
    RECIPES_IMAGE_FOLDER = 'recipes'
