# Generated by Django 3.2.18 on 2023-04-21 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='subscribes',
            new_name='subscribe',
        ),
    ]
