# Generated by Django 3.2.18 on 2023-04-26 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_subscribes_subscribe_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='subscribe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
