# Generated by Django 3.2.18 on 2023-05-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_subscribe_subscribe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={'verbose_name': 'Subscribe', 'verbose_name_plural': 'Subscribes'},
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Set user name please', max_length=254, unique=True, verbose_name='Unique username'),
        ),
        migrations.AlterUniqueTogether(
            name='subscribe',
            unique_together={('user', 'subscribe')},
        ),
    ]
